App\Domain\Model\Entity\Permission:
  type: entity
  repositoryClass: App\Infrastructure\Persistence\Doctrine\Repository\DoctrinePermissionRepository
  table: permissions
  schema: yabe
  readOnly: false
  gedmo:
    soft_deleteable:
      field_name: deletedAt
      time_aware: true
  id:
    id:
      type: uuid
      generator:
          strategy: CUSTOM
      customIdGenerator:
          class: Ramsey\Uuid\Doctrine\UuidGenerator
  fields:
    name:
      type: string
      length: 50
      nullable: false
      unique: true
    objectType:
      type: string
      length: 50
      nullable: false
      column: object_type
    actionType:
      type: string
      length: 50
      nullable: false
      column: action_type
    objectId:
      type: string
      length: 50
      nullable: false
      column: object_id
    createdAt:
      type: datetime
      nullable: true
      column: created_at
      gedmo:
        timestampable:
          on: create
    updatedAt:
      type: datetime
      nullable: true
      column: updated_at
      gedmo:
        timestampable:
          on: update
    deletedAt:
      type: datetime
      nullable: true
      column: deleted_at