App\Domain\Model\Entity\Post:
  type: entity
  repositoryClass: App\Infrastructure\Persistence\Doctrine\Repository\DoctrinePostRepository
  table: posts
  schema: yabe
  readOnly: false
  gedmo:
    soft_deleteable:
      field_name: deletedAt
      time_aware: true
  id:
    id:
      type: uuid
      generator:
          strategy: CUSTOM
      customIdGenerator:
          class: Ramsey\Uuid\Doctrine\UuidGenerator
  fields:
    title:
      type: string
      length: 2000
      nullable: false
    slug:
      type: string
      length: 191
      nullable: false
      unique: true
    mobiledoc:
      type: text
      nullable: true
    html:
      type: text
      nullable: true
    amp:
      type: text
      nullable: true
    plaintext:
      type: text
      nullable: true
    featureImage:
      type: string
      length: 2000
      nullable: true
      column: feature_image
    featured:
      type: boolean
      nullable: false
      options:
        default: 0
    page:
      type: boolean
      nullable: false
      options:
        default: 0
    status:
      type: string
      length: 50
      nullable: false
      options:
        default: draft
    locale:
      type: string
      length: 6
      nullable: true
    visibility:
      type: string
      length: 50
      nullable: false
      options:
        default: public
    metaTitle:
      type: string
      length: 2000
      nullable: true
      column: meta_title
    metaDescription:
      type: string
      length: 2000
      nullable: true
      column: meta_description
    customExcerpt:
      type: string
      length: 2000
      nullable: true
      column: custom_excerpt
    codeInjectionHead:
      type: text
      nullable: true
      column: codeinjection_head
    codeInjectionFoot:
      type: text
      nullable: true
      column: codeinjection_foot
    ogImage:
      type: string
      length: 2000
      nullable: true
      column: og_image
    ogTitle:
      type: string
      length: 300
      nullable: true
      column: og_title
    ogDescription:
      type: string
      length: 500
      nullable: true
      column: og_description
    twitterImage:
      type: string
      length: 2000
      nullable: true
      column: twitter_image
    twitterTitle:
      type: string
      length: 300
      nullable: true
      column: twitter_title
    twitterDescription:
      type: string
      length: 500
      nullable: true
      column: twitter_description
    customTemplate:
      type: string
      length: 100
      nullable: true
      column: custom_template
    publishedAt:
      type: datetime
      nullable: true
      column: published_at
      gedmo:
        timestampable:
          on: publish
    createdAt:
      type: datetime
      nullable: true
      column: created_at
      gedmo:
        timestampable:
          on: create
    updatedAt:
      type: datetime
      nullable: true
      column: updated_at
      gedmo:
        timestampable:
          on: update
    deletedAt:
      type: datetime
      nullable: true
      column: deleted_at
  manyToOne:
    author:
      targetEntity: User
      inversedBy: posts
      joinColumn:
        name: author_id
        referencedColumnName: id
    publishedBy:
      targetEntity: User
      joinColumn:
        name: published_by
        referencedColumnName: id
    createdBy:
      targetEntity: User
      joinColumn:
        name: created_by
        referencedColumnName: id
    updatedBy:
      targetEntity: User
      joinColumn:
        name: updated_by
        referencedColumnName: id
    deletedBy:
      targetEntity: User
      joinColumn:
        name: deleted_by
        referencedColumnName: id
  manyToMany:
    tags:
      targetEntity: Tag
      inversedBy: posts
      joinTable:
        name: post_tags
        joinColumns:
          post_id:
            referencedColumnName: id
        inverseJoinColumns:
          tag_id:
            referencedColumnName: id